### ISSUE TITLE
Zero Gravity Mode for Jaco Arms

### ISSUE THREAD

**Issue by stefie10** [Kinovarobotics/kinova-movo#34]
Hi,

Is there a way to access zero G mode for the Jaco arms on Movo?  I recall seeing something about this in the Jaco API docs, but I don't see anything in the Movo Repo.  I'd like to put the arms in a mode where they compensate for their own weight, but allow a person to physically drive them into different configurations.

Thanks!

Stefanie

**Comment by martine1406** [comment]
Hi @stefie10 

Unfortunately, this mode is not yet available on the movo. However, it is not super hard to implement. First, you'll have to set the gravity vector in the right orientation since the arms are mounted horizontally. The C++ API function to do so is SetGravityVector. The base axis system for the Kinova arms is defined as shown below:

![image](https://user-images.githubusercontent.com/23724061/39412339-b59c8c94-4be8-11e8-86fb-a53cbd248a35.png)

Then, you will need to activate the Reactive force control mode. The C++ API function to do so is SetForceControl.

Finally, you have functions to customize the Reactive force control: SetCartesianForceMinMax, SetCartesianInertiaDamping

Reactive force control will allow you to grab the robot by its hand and move it around (I think this is the best option considering what you want to do). The other option instead of using the Reactive force control is to use the torque control. In this mode, the robot is really in the zero G mode, but it is very very sensitive and since the torque sensors are not perfect, I would recommend to use the Reactive force control instead. The Reactive force control will give you the impression of being in torque mode but with some damping. 

To know more about Kinova API functions and what they can offer, you can download the Kinova SDK from the kinova website: http://www.kinovarobotics.com/innovation-robotics/support/?section=resources and then you will have access to the Kinova API html documentation. 

As you can see, movo uses a python wrapper of the Kinova C++ API ([here](https://github.com/Kinovarobotics/kinova-movo/blob/master/movo_common/movo_ros/src/movo_joint_interface/kinova_api_wrapper.py)). Unfortunately, not all the Kinova API functions were implemented in that wrapper yet.  

Thank you
Martine
